# Generated by Django 2.2.6 on 2019-10-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_adress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
