# Generated by Django 2.2.8 on 2020-01-24 03:27

from django.db import migrations, models
from django.utils.text import slugify

class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        User = apps.get_model("account", "User")
        for instance in User.objects.all():
            if not instance.slug:
                name = instance.email.split('@')[0]
                slug = '-'.join(name.split('.'))
                instance.slug = slugify(slug)
                instance.save()

    def reverse_func(apps, schema_editor):
        pass


    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
